// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Webapi.DataAccess;

#nullable disable

namespace TodoApp.Webapi.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TodoApp.Webapi.DataAccess.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47e174d8-1350-4a00-bd49-d8b1fc5bf1d0"),
                            CreatedDate = new DateTime(2023, 11, 30, 22, 36, 25, 714, DateTimeKind.Local).AddTicks(4490),
                            IsDeleted = false,
                            Title = "Excercise"
                        },
                        new
                        {
                            Id = new Guid("2f91cb78-313d-4def-b795-2c3ea982ff3d"),
                            CreatedDate = new DateTime(2023, 11, 30, 22, 36, 25, 714, DateTimeKind.Local).AddTicks(4507),
                            IsDeleted = false,
                            Title = "Cooking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
